// Autogenerated from Pigeon (v1.0.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface DTGBasicIdMessage ()
+ (DTGBasicIdMessage *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGLocationMessage ()
+ (DTGLocationMessage *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGOperatorIdMessage ()
+ (DTGOperatorIdMessage *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation DTGBasicIdMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    uasId:(NSString *)uasId
    idType:(DTGIdType)idType
    uaType:(DTGUaType)uaType {
  DTGBasicIdMessage* pigeonResult = [[DTGBasicIdMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.uasId = uasId;
  pigeonResult.idType = idType;
  pigeonResult.uaType = uaType;
  return pigeonResult;
}
+ (DTGBasicIdMessage *)fromMap:(NSDictionary *)dict {
  DTGBasicIdMessage *pigeonResult = [[DTGBasicIdMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.uasId = GetNullableObject(dict, @"uasId");
  NSAssert(pigeonResult.uasId != nil, @"");
  pigeonResult.idType = [GetNullableObject(dict, @"idType") integerValue];
  pigeonResult.uaType = [GetNullableObject(dict, @"uaType") integerValue];
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.receivedTimestamp ? self.receivedTimestamp : [NSNull null]), @"receivedTimestamp", (self.macAddress ? self.macAddress : [NSNull null]), @"macAddress", @(self.source), @"source", (self.rssi ? self.rssi : [NSNull null]), @"rssi", (self.uasId ? self.uasId : [NSNull null]), @"uasId", @(self.idType), @"idType", @(self.uaType), @"uaType", nil];
}
@end

@implementation DTGLocationMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    status:(DTGAircraftStatus)status
    heightType:(DTGHeightType)heightType
    direction:(nullable NSNumber *)direction
    speedHorizontal:(nullable NSNumber *)speedHorizontal
    speedVertical:(nullable NSNumber *)speedVertical
    latitude:(nullable NSNumber *)latitude
    longitude:(nullable NSNumber *)longitude
    altitudePressure:(nullable NSNumber *)altitudePressure
    altitudeGeodetic:(nullable NSNumber *)altitudeGeodetic
    height:(nullable NSNumber *)height
    horizontalAccuracy:(DTGHorizontalAccuracy)horizontalAccuracy
    verticalAccuracy:(DTGVerticalAccuracy)verticalAccuracy
    baroAccuracy:(DTGVerticalAccuracy)baroAccuracy
    speedAccuracy:(DTGSpeedAccuracy)speedAccuracy
    time:(nullable NSNumber *)time
    timeAccuracy:(nullable NSNumber *)timeAccuracy {
  DTGLocationMessage* pigeonResult = [[DTGLocationMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.status = status;
  pigeonResult.heightType = heightType;
  pigeonResult.direction = direction;
  pigeonResult.speedHorizontal = speedHorizontal;
  pigeonResult.speedVertical = speedVertical;
  pigeonResult.latitude = latitude;
  pigeonResult.longitude = longitude;
  pigeonResult.altitudePressure = altitudePressure;
  pigeonResult.altitudeGeodetic = altitudeGeodetic;
  pigeonResult.height = height;
  pigeonResult.horizontalAccuracy = horizontalAccuracy;
  pigeonResult.verticalAccuracy = verticalAccuracy;
  pigeonResult.baroAccuracy = baroAccuracy;
  pigeonResult.speedAccuracy = speedAccuracy;
  pigeonResult.time = time;
  pigeonResult.timeAccuracy = timeAccuracy;
  return pigeonResult;
}
+ (DTGLocationMessage *)fromMap:(NSDictionary *)dict {
  DTGLocationMessage *pigeonResult = [[DTGLocationMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.status = [GetNullableObject(dict, @"status") integerValue];
  pigeonResult.heightType = [GetNullableObject(dict, @"heightType") integerValue];
  pigeonResult.direction = GetNullableObject(dict, @"direction");
  pigeonResult.speedHorizontal = GetNullableObject(dict, @"speedHorizontal");
  pigeonResult.speedVertical = GetNullableObject(dict, @"speedVertical");
  pigeonResult.latitude = GetNullableObject(dict, @"latitude");
  pigeonResult.longitude = GetNullableObject(dict, @"longitude");
  pigeonResult.altitudePressure = GetNullableObject(dict, @"altitudePressure");
  pigeonResult.altitudeGeodetic = GetNullableObject(dict, @"altitudeGeodetic");
  pigeonResult.height = GetNullableObject(dict, @"height");
  pigeonResult.horizontalAccuracy = [GetNullableObject(dict, @"horizontalAccuracy") integerValue];
  pigeonResult.verticalAccuracy = [GetNullableObject(dict, @"verticalAccuracy") integerValue];
  pigeonResult.baroAccuracy = [GetNullableObject(dict, @"baroAccuracy") integerValue];
  pigeonResult.speedAccuracy = [GetNullableObject(dict, @"speedAccuracy") integerValue];
  pigeonResult.time = GetNullableObject(dict, @"time");
  pigeonResult.timeAccuracy = GetNullableObject(dict, @"timeAccuracy");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.receivedTimestamp ? self.receivedTimestamp : [NSNull null]), @"receivedTimestamp", (self.macAddress ? self.macAddress : [NSNull null]), @"macAddress", @(self.source), @"source", (self.rssi ? self.rssi : [NSNull null]), @"rssi", @(self.status), @"status", @(self.heightType), @"heightType", (self.direction ? self.direction : [NSNull null]), @"direction", (self.speedHorizontal ? self.speedHorizontal : [NSNull null]), @"speedHorizontal", (self.speedVertical ? self.speedVertical : [NSNull null]), @"speedVertical", (self.latitude ? self.latitude : [NSNull null]), @"latitude", (self.longitude ? self.longitude : [NSNull null]), @"longitude", (self.altitudePressure ? self.altitudePressure : [NSNull null]), @"altitudePressure", (self.altitudeGeodetic ? self.altitudeGeodetic : [NSNull null]), @"altitudeGeodetic", (self.height ? self.height : [NSNull null]), @"height", @(self.horizontalAccuracy), @"horizontalAccuracy", @(self.verticalAccuracy), @"verticalAccuracy", @(self.baroAccuracy), @"baroAccuracy", @(self.speedAccuracy), @"speedAccuracy", (self.time ? self.time : [NSNull null]), @"time", (self.timeAccuracy ? self.timeAccuracy : [NSNull null]), @"timeAccuracy", nil];
}
@end

@implementation DTGOperatorIdMessage
+ (instancetype)makeWithMacAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    operatorId:(NSString *)operatorId {
  DTGOperatorIdMessage* pigeonResult = [[DTGOperatorIdMessage alloc] init];
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.operatorId = operatorId;
  return pigeonResult;
}
+ (DTGOperatorIdMessage *)fromMap:(NSDictionary *)dict {
  DTGOperatorIdMessage *pigeonResult = [[DTGOperatorIdMessage alloc] init];
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.operatorId = GetNullableObject(dict, @"operatorId");
  NSAssert(pigeonResult.operatorId != nil, @"");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.macAddress ? self.macAddress : [NSNull null]), @"macAddress", @(self.source), @"source", (self.rssi ? self.rssi : [NSNull null]), @"rssi", (self.operatorId ? self.operatorId : [NSNull null]), @"operatorId", nil];
}
@end

@interface DTGApiCodecReader : FlutterStandardReader
@end
@implementation DTGApiCodecReader
@end

@interface DTGApiCodecWriter : FlutterStandardWriter
@end
@implementation DTGApiCodecWriter
@end

@interface DTGApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DTGApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DTGApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DTGApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DTGApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    DTGApiCodecReaderWriter *readerWriter = [[DTGApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void DTGApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTGApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.startScan"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startScanWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(startScanWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api startScanWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.stopScan"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopScanWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(stopScanWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api stopScanWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.setAutorestart"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setAutorestartEnable:completion:)], @"DTGApi api (%@) doesn't respond to @selector(setAutorestartEnable:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_enable = args[0];
        [api setAutorestartEnable:arg_enable completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.isScanning"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isScanningWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(isScanningWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api isScanningWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.bluetoothState"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(bluetoothStateWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(bluetoothStateWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api bluetoothStateWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface DTGMessageApiCodecReader : FlutterStandardReader
@end
@implementation DTGMessageApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [DTGBasicIdMessage fromMap:[self readValue]];
    
    case 129:     
      return [DTGLocationMessage fromMap:[self readValue]];
    
    case 130:     
      return [DTGOperatorIdMessage fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface DTGMessageApiCodecWriter : FlutterStandardWriter
@end
@implementation DTGMessageApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[DTGBasicIdMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGLocationMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGOperatorIdMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface DTGMessageApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DTGMessageApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DTGMessageApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DTGMessageApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DTGMessageApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    DTGMessageApiCodecReaderWriter *readerWriter = [[DTGMessageApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void DTGMessageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTGMessageApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.MessageApi.determineMessageType"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(determineMessageTypePayload:offset:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(determineMessageTypePayload:offset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = args[0];
        NSNumber *arg_offset = args[1];
        FlutterError *error;
        NSNumber *output = [api determineMessageTypePayload:arg_payload offset:arg_offset error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.MessageApi.fromBufferBasic"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferBasicPayload:offset:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferBasicPayload:offset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = args[0];
        NSNumber *arg_offset = args[1];
        FlutterError *error;
        DTGBasicIdMessage *output = [api fromBufferBasicPayload:arg_payload offset:arg_offset error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.MessageApi.fromBufferLocation"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferLocationPayload:offset:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferLocationPayload:offset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = args[0];
        NSNumber *arg_offset = args[1];
        FlutterError *error;
        DTGLocationMessage *output = [api fromBufferLocationPayload:arg_payload offset:arg_offset error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.MessageApi.fromBufferOperatorId"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferOperatorIdPayload:offset:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferOperatorIdPayload:offset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = args[0];
        NSNumber *arg_offset = args[1];
        FlutterError *error;
        DTGOperatorIdMessage *output = [api fromBufferOperatorIdPayload:arg_payload offset:arg_offset error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
