// Autogenerated from Pigeon (v3.2.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface DTGBasicIdMessage ()
+ (DTGBasicIdMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGBasicIdMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGLocationMessage ()
+ (DTGLocationMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGLocationMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGOperatorIdMessage ()
+ (DTGOperatorIdMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGOperatorIdMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGAuthenticationMessage ()
+ (DTGAuthenticationMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGAuthenticationMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGSelfIdMessage ()
+ (DTGSelfIdMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGSelfIdMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGSystemDataMessage ()
+ (DTGSystemDataMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGSystemDataMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DTGConnectionMessage ()
+ (DTGConnectionMessage *)fromMap:(NSDictionary *)dict;
+ (nullable DTGConnectionMessage *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation DTGBasicIdMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    uasId:(NSString *)uasId
    idType:(DTGIdType)idType
    uaType:(DTGUaType)uaType {
  DTGBasicIdMessage* pigeonResult = [[DTGBasicIdMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.uasId = uasId;
  pigeonResult.idType = idType;
  pigeonResult.uaType = uaType;
  return pigeonResult;
}
+ (DTGBasicIdMessage *)fromMap:(NSDictionary *)dict {
  DTGBasicIdMessage *pigeonResult = [[DTGBasicIdMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.uasId = GetNullableObject(dict, @"uasId");
  NSAssert(pigeonResult.uasId != nil, @"");
  pigeonResult.idType = [GetNullableObject(dict, @"idType") integerValue];
  pigeonResult.uaType = [GetNullableObject(dict, @"uaType") integerValue];
  return pigeonResult;
}
+ (nullable DTGBasicIdMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGBasicIdMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"uasId" : (self.uasId ?: [NSNull null]),
    @"idType" : @(self.idType),
    @"uaType" : @(self.uaType),
  };
}
@end

@implementation DTGLocationMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    status:(DTGAircraftStatus)status
    heightType:(DTGHeightType)heightType
    direction:(nullable NSNumber *)direction
    speedHorizontal:(nullable NSNumber *)speedHorizontal
    speedVertical:(nullable NSNumber *)speedVertical
    latitude:(nullable NSNumber *)latitude
    longitude:(nullable NSNumber *)longitude
    altitudePressure:(nullable NSNumber *)altitudePressure
    altitudeGeodetic:(nullable NSNumber *)altitudeGeodetic
    height:(nullable NSNumber *)height
    horizontalAccuracy:(DTGHorizontalAccuracy)horizontalAccuracy
    verticalAccuracy:(DTGVerticalAccuracy)verticalAccuracy
    baroAccuracy:(DTGVerticalAccuracy)baroAccuracy
    speedAccuracy:(DTGSpeedAccuracy)speedAccuracy
    time:(nullable NSNumber *)time
    timeAccuracy:(nullable NSNumber *)timeAccuracy {
  DTGLocationMessage* pigeonResult = [[DTGLocationMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.status = status;
  pigeonResult.heightType = heightType;
  pigeonResult.direction = direction;
  pigeonResult.speedHorizontal = speedHorizontal;
  pigeonResult.speedVertical = speedVertical;
  pigeonResult.latitude = latitude;
  pigeonResult.longitude = longitude;
  pigeonResult.altitudePressure = altitudePressure;
  pigeonResult.altitudeGeodetic = altitudeGeodetic;
  pigeonResult.height = height;
  pigeonResult.horizontalAccuracy = horizontalAccuracy;
  pigeonResult.verticalAccuracy = verticalAccuracy;
  pigeonResult.baroAccuracy = baroAccuracy;
  pigeonResult.speedAccuracy = speedAccuracy;
  pigeonResult.time = time;
  pigeonResult.timeAccuracy = timeAccuracy;
  return pigeonResult;
}
+ (DTGLocationMessage *)fromMap:(NSDictionary *)dict {
  DTGLocationMessage *pigeonResult = [[DTGLocationMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.status = [GetNullableObject(dict, @"status") integerValue];
  pigeonResult.heightType = [GetNullableObject(dict, @"heightType") integerValue];
  pigeonResult.direction = GetNullableObject(dict, @"direction");
  pigeonResult.speedHorizontal = GetNullableObject(dict, @"speedHorizontal");
  pigeonResult.speedVertical = GetNullableObject(dict, @"speedVertical");
  pigeonResult.latitude = GetNullableObject(dict, @"latitude");
  pigeonResult.longitude = GetNullableObject(dict, @"longitude");
  pigeonResult.altitudePressure = GetNullableObject(dict, @"altitudePressure");
  pigeonResult.altitudeGeodetic = GetNullableObject(dict, @"altitudeGeodetic");
  pigeonResult.height = GetNullableObject(dict, @"height");
  pigeonResult.horizontalAccuracy = [GetNullableObject(dict, @"horizontalAccuracy") integerValue];
  pigeonResult.verticalAccuracy = [GetNullableObject(dict, @"verticalAccuracy") integerValue];
  pigeonResult.baroAccuracy = [GetNullableObject(dict, @"baroAccuracy") integerValue];
  pigeonResult.speedAccuracy = [GetNullableObject(dict, @"speedAccuracy") integerValue];
  pigeonResult.time = GetNullableObject(dict, @"time");
  pigeonResult.timeAccuracy = GetNullableObject(dict, @"timeAccuracy");
  return pigeonResult;
}
+ (nullable DTGLocationMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGLocationMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"status" : @(self.status),
    @"heightType" : @(self.heightType),
    @"direction" : (self.direction ?: [NSNull null]),
    @"speedHorizontal" : (self.speedHorizontal ?: [NSNull null]),
    @"speedVertical" : (self.speedVertical ?: [NSNull null]),
    @"latitude" : (self.latitude ?: [NSNull null]),
    @"longitude" : (self.longitude ?: [NSNull null]),
    @"altitudePressure" : (self.altitudePressure ?: [NSNull null]),
    @"altitudeGeodetic" : (self.altitudeGeodetic ?: [NSNull null]),
    @"height" : (self.height ?: [NSNull null]),
    @"horizontalAccuracy" : @(self.horizontalAccuracy),
    @"verticalAccuracy" : @(self.verticalAccuracy),
    @"baroAccuracy" : @(self.baroAccuracy),
    @"speedAccuracy" : @(self.speedAccuracy),
    @"time" : (self.time ?: [NSNull null]),
    @"timeAccuracy" : (self.timeAccuracy ?: [NSNull null]),
  };
}
@end

@implementation DTGOperatorIdMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    operatorId:(NSString *)operatorId {
  DTGOperatorIdMessage* pigeonResult = [[DTGOperatorIdMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.operatorId = operatorId;
  return pigeonResult;
}
+ (DTGOperatorIdMessage *)fromMap:(NSDictionary *)dict {
  DTGOperatorIdMessage *pigeonResult = [[DTGOperatorIdMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.operatorId = GetNullableObject(dict, @"operatorId");
  NSAssert(pigeonResult.operatorId != nil, @"");
  return pigeonResult;
}
+ (nullable DTGOperatorIdMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGOperatorIdMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"operatorId" : (self.operatorId ?: [NSNull null]),
  };
}
@end

@implementation DTGAuthenticationMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    authType:(DTGAuthType)authType
    authDataPage:(NSNumber *)authDataPage
    authLastPageIndex:(NSNumber *)authLastPageIndex
    authLength:(NSNumber *)authLength
    authTimestamp:(NSNumber *)authTimestamp
    authData:(NSString *)authData {
  DTGAuthenticationMessage* pigeonResult = [[DTGAuthenticationMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.authType = authType;
  pigeonResult.authDataPage = authDataPage;
  pigeonResult.authLastPageIndex = authLastPageIndex;
  pigeonResult.authLength = authLength;
  pigeonResult.authTimestamp = authTimestamp;
  pigeonResult.authData = authData;
  return pigeonResult;
}
+ (DTGAuthenticationMessage *)fromMap:(NSDictionary *)dict {
  DTGAuthenticationMessage *pigeonResult = [[DTGAuthenticationMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.authType = [GetNullableObject(dict, @"authType") integerValue];
  pigeonResult.authDataPage = GetNullableObject(dict, @"authDataPage");
  NSAssert(pigeonResult.authDataPage != nil, @"");
  pigeonResult.authLastPageIndex = GetNullableObject(dict, @"authLastPageIndex");
  NSAssert(pigeonResult.authLastPageIndex != nil, @"");
  pigeonResult.authLength = GetNullableObject(dict, @"authLength");
  NSAssert(pigeonResult.authLength != nil, @"");
  pigeonResult.authTimestamp = GetNullableObject(dict, @"authTimestamp");
  NSAssert(pigeonResult.authTimestamp != nil, @"");
  pigeonResult.authData = GetNullableObject(dict, @"authData");
  NSAssert(pigeonResult.authData != nil, @"");
  return pigeonResult;
}
+ (nullable DTGAuthenticationMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGAuthenticationMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"authType" : @(self.authType),
    @"authDataPage" : (self.authDataPage ?: [NSNull null]),
    @"authLastPageIndex" : (self.authLastPageIndex ?: [NSNull null]),
    @"authLength" : (self.authLength ?: [NSNull null]),
    @"authTimestamp" : (self.authTimestamp ?: [NSNull null]),
    @"authData" : (self.authData ?: [NSNull null]),
  };
}
@end

@implementation DTGSelfIdMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    descriptionType:(NSNumber *)descriptionType
    operationDescription:(NSString *)operationDescription {
  DTGSelfIdMessage* pigeonResult = [[DTGSelfIdMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.descriptionType = descriptionType;
  pigeonResult.operationDescription = operationDescription;
  return pigeonResult;
}
+ (DTGSelfIdMessage *)fromMap:(NSDictionary *)dict {
  DTGSelfIdMessage *pigeonResult = [[DTGSelfIdMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.descriptionType = GetNullableObject(dict, @"descriptionType");
  NSAssert(pigeonResult.descriptionType != nil, @"");
  pigeonResult.operationDescription = GetNullableObject(dict, @"operationDescription");
  NSAssert(pigeonResult.operationDescription != nil, @"");
  return pigeonResult;
}
+ (nullable DTGSelfIdMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGSelfIdMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"descriptionType" : (self.descriptionType ?: [NSNull null]),
    @"operationDescription" : (self.operationDescription ?: [NSNull null]),
  };
}
@end

@implementation DTGSystemDataMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    operatorLocationType:(DTGOperatorLocationType)operatorLocationType
    classificationType:(DTGClassificationType)classificationType
    operatorLatitude:(NSNumber *)operatorLatitude
    operatorLongitude:(NSNumber *)operatorLongitude
    areaCount:(NSNumber *)areaCount
    areaRadius:(NSNumber *)areaRadius
    areaCeiling:(NSNumber *)areaCeiling
    areaFloor:(NSNumber *)areaFloor
    category:(DTGAircraftCategory)category
    classValue:(DTGAircraftClass)classValue
    operatorAltitudeGeo:(NSNumber *)operatorAltitudeGeo {
  DTGSystemDataMessage* pigeonResult = [[DTGSystemDataMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.operatorLocationType = operatorLocationType;
  pigeonResult.classificationType = classificationType;
  pigeonResult.operatorLatitude = operatorLatitude;
  pigeonResult.operatorLongitude = operatorLongitude;
  pigeonResult.areaCount = areaCount;
  pigeonResult.areaRadius = areaRadius;
  pigeonResult.areaCeiling = areaCeiling;
  pigeonResult.areaFloor = areaFloor;
  pigeonResult.category = category;
  pigeonResult.classValue = classValue;
  pigeonResult.operatorAltitudeGeo = operatorAltitudeGeo;
  return pigeonResult;
}
+ (DTGSystemDataMessage *)fromMap:(NSDictionary *)dict {
  DTGSystemDataMessage *pigeonResult = [[DTGSystemDataMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.operatorLocationType = [GetNullableObject(dict, @"operatorLocationType") integerValue];
  pigeonResult.classificationType = [GetNullableObject(dict, @"classificationType") integerValue];
  pigeonResult.operatorLatitude = GetNullableObject(dict, @"operatorLatitude");
  NSAssert(pigeonResult.operatorLatitude != nil, @"");
  pigeonResult.operatorLongitude = GetNullableObject(dict, @"operatorLongitude");
  NSAssert(pigeonResult.operatorLongitude != nil, @"");
  pigeonResult.areaCount = GetNullableObject(dict, @"areaCount");
  NSAssert(pigeonResult.areaCount != nil, @"");
  pigeonResult.areaRadius = GetNullableObject(dict, @"areaRadius");
  NSAssert(pigeonResult.areaRadius != nil, @"");
  pigeonResult.areaCeiling = GetNullableObject(dict, @"areaCeiling");
  NSAssert(pigeonResult.areaCeiling != nil, @"");
  pigeonResult.areaFloor = GetNullableObject(dict, @"areaFloor");
  NSAssert(pigeonResult.areaFloor != nil, @"");
  pigeonResult.category = [GetNullableObject(dict, @"category") integerValue];
  pigeonResult.classValue = [GetNullableObject(dict, @"classValue") integerValue];
  pigeonResult.operatorAltitudeGeo = GetNullableObject(dict, @"operatorAltitudeGeo");
  NSAssert(pigeonResult.operatorAltitudeGeo != nil, @"");
  return pigeonResult;
}
+ (nullable DTGSystemDataMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGSystemDataMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"operatorLocationType" : @(self.operatorLocationType),
    @"classificationType" : @(self.classificationType),
    @"operatorLatitude" : (self.operatorLatitude ?: [NSNull null]),
    @"operatorLongitude" : (self.operatorLongitude ?: [NSNull null]),
    @"areaCount" : (self.areaCount ?: [NSNull null]),
    @"areaRadius" : (self.areaRadius ?: [NSNull null]),
    @"areaCeiling" : (self.areaCeiling ?: [NSNull null]),
    @"areaFloor" : (self.areaFloor ?: [NSNull null]),
    @"category" : @(self.category),
    @"classValue" : @(self.classValue),
    @"operatorAltitudeGeo" : (self.operatorAltitudeGeo ?: [NSNull null]),
  };
}
@end

@implementation DTGConnectionMessage
+ (instancetype)makeWithReceivedTimestamp:(NSNumber *)receivedTimestamp
    macAddress:(NSString *)macAddress
    source:(DTGMessageSource)source
    rssi:(nullable NSNumber *)rssi
    transportType:(NSString *)transportType
    lastSeen:(NSNumber *)lastSeen
    firstSeen:(NSNumber *)firstSeen
    msgDelta:(NSNumber *)msgDelta {
  DTGConnectionMessage* pigeonResult = [[DTGConnectionMessage alloc] init];
  pigeonResult.receivedTimestamp = receivedTimestamp;
  pigeonResult.macAddress = macAddress;
  pigeonResult.source = source;
  pigeonResult.rssi = rssi;
  pigeonResult.transportType = transportType;
  pigeonResult.lastSeen = lastSeen;
  pigeonResult.firstSeen = firstSeen;
  pigeonResult.msgDelta = msgDelta;
  return pigeonResult;
}
+ (DTGConnectionMessage *)fromMap:(NSDictionary *)dict {
  DTGConnectionMessage *pigeonResult = [[DTGConnectionMessage alloc] init];
  pigeonResult.receivedTimestamp = GetNullableObject(dict, @"receivedTimestamp");
  NSAssert(pigeonResult.receivedTimestamp != nil, @"");
  pigeonResult.macAddress = GetNullableObject(dict, @"macAddress");
  NSAssert(pigeonResult.macAddress != nil, @"");
  pigeonResult.source = [GetNullableObject(dict, @"source") integerValue];
  pigeonResult.rssi = GetNullableObject(dict, @"rssi");
  pigeonResult.transportType = GetNullableObject(dict, @"transportType");
  NSAssert(pigeonResult.transportType != nil, @"");
  pigeonResult.lastSeen = GetNullableObject(dict, @"lastSeen");
  NSAssert(pigeonResult.lastSeen != nil, @"");
  pigeonResult.firstSeen = GetNullableObject(dict, @"firstSeen");
  NSAssert(pigeonResult.firstSeen != nil, @"");
  pigeonResult.msgDelta = GetNullableObject(dict, @"msgDelta");
  NSAssert(pigeonResult.msgDelta != nil, @"");
  return pigeonResult;
}
+ (nullable DTGConnectionMessage *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [DTGConnectionMessage fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"receivedTimestamp" : (self.receivedTimestamp ?: [NSNull null]),
    @"macAddress" : (self.macAddress ?: [NSNull null]),
    @"source" : @(self.source),
    @"rssi" : (self.rssi ?: [NSNull null]),
    @"transportType" : (self.transportType ?: [NSNull null]),
    @"lastSeen" : (self.lastSeen ?: [NSNull null]),
    @"firstSeen" : (self.firstSeen ?: [NSNull null]),
    @"msgDelta" : (self.msgDelta ?: [NSNull null]),
  };
}
@end

@interface DTGApiCodecReader : FlutterStandardReader
@end
@implementation DTGApiCodecReader
@end

@interface DTGApiCodecWriter : FlutterStandardWriter
@end
@implementation DTGApiCodecWriter
@end

@interface DTGApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DTGApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DTGApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DTGApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DTGApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    DTGApiCodecReaderWriter *readerWriter = [[DTGApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void DTGApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTGApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.startScanBluetooth"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startScanBluetoothWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(startScanBluetoothWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api startScanBluetoothWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.startScanWifi"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startScanWifiWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(startScanWifiWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api startScanWifiWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.stopScanBluetooth"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopScanBluetoothWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(stopScanBluetoothWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api stopScanBluetoothWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.stopScanWifi"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopScanWifiWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(stopScanWifiWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api stopScanWifiWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.setBtScanPriority"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setBtScanPriorityPriority:completion:)], @"DTGApi api (%@) doesn't respond to @selector(setBtScanPriorityPriority:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        DTGScanPriority arg_priority = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api setBtScanPriorityPriority:arg_priority completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.isScanningBluetooth"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isScanningBluetoothWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(isScanningBluetoothWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api isScanningBluetoothWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.isScanningWifi"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isScanningWifiWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(isScanningWifiWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api isScanningWifiWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.bluetoothState"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(bluetoothStateWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(bluetoothStateWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api bluetoothStateWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.wifiState"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(wifiStateWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(wifiStateWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api wifiStateWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.btExtendedSupported"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(btExtendedSupportedWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(btExtendedSupportedWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api btExtendedSupportedWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.btMaxAdvDataLen"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(btMaxAdvDataLenWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(btMaxAdvDataLenWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api btMaxAdvDataLenWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Api.wifiNaNSupported"
        binaryMessenger:binaryMessenger
        codec:DTGApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(wifiNaNSupportedWithCompletion:)], @"DTGApi api (%@) doesn't respond to @selector(wifiNaNSupportedWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api wifiNaNSupportedWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface DTGMessageApiCodecReader : FlutterStandardReader
@end
@implementation DTGMessageApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [DTGAuthenticationMessage fromMap:[self readValue]];
    
    case 129:     
      return [DTGBasicIdMessage fromMap:[self readValue]];
    
    case 130:     
      return [DTGConnectionMessage fromMap:[self readValue]];
    
    case 131:     
      return [DTGLocationMessage fromMap:[self readValue]];
    
    case 132:     
      return [DTGOperatorIdMessage fromMap:[self readValue]];
    
    case 133:     
      return [DTGSelfIdMessage fromMap:[self readValue]];
    
    case 134:     
      return [DTGSystemDataMessage fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface DTGMessageApiCodecWriter : FlutterStandardWriter
@end
@implementation DTGMessageApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[DTGAuthenticationMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGBasicIdMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGConnectionMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGLocationMessage class]]) {
    [self writeByte:131];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGOperatorIdMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGSelfIdMessage class]]) {
    [self writeByte:133];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DTGSystemDataMessage class]]) {
    [self writeByte:134];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface DTGMessageApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DTGMessageApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DTGMessageApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DTGMessageApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DTGMessageApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    DTGMessageApiCodecReaderWriter *readerWriter = [[DTGMessageApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void DTGMessageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTGMessageApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.determineMessageType"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(determineMessageTypePayload:offset:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(determineMessageTypePayload:offset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        NSNumber *output = [api determineMessageTypePayload:arg_payload offset:arg_offset error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferBasic"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferBasicPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferBasicPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGBasicIdMessage *output = [api fromBufferBasicPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferLocation"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferLocationPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferLocationPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGLocationMessage *output = [api fromBufferLocationPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferOperatorId"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferOperatorIdPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferOperatorIdPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGOperatorIdMessage *output = [api fromBufferOperatorIdPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferSelfId"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferSelfIdPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferSelfIdPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGSelfIdMessage *output = [api fromBufferSelfIdPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferAuthentication"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferAuthenticationPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferAuthenticationPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGAuthenticationMessage *output = [api fromBufferAuthenticationPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferSystemData"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferSystemDataPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferSystemDataPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGSystemDataMessage *output = [api fromBufferSystemDataPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.fromBufferConnection"
        binaryMessenger:binaryMessenger
        codec:DTGMessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fromBufferConnectionPayload:offset:macAddress:error:)], @"DTGMessageApi api (%@) doesn't respond to @selector(fromBufferConnectionPayload:offset:macAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_payload = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_offset = GetNullableObjectAtIndex(args, 1);
        NSString *arg_macAddress = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        DTGConnectionMessage *output = [api fromBufferConnectionPayload:arg_payload offset:arg_offset macAddress:arg_macAddress error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
