const MAX_MESSAGE_SIZE = 25;
const MAX_ID_BYTE_SIZE = 20;
const MAX_STRING_BYTE_SIZE = 23;
const MAX_AUTH_DATA_PAGES = 16;
const MAX_AUTH_PAGE_ZERO_SIZE = 17;
const MAX_AUTH_PAGE_NON_ZERO_SIZE = 23;
const MAX_AUTH_DATA = MAX_AUTH_PAGE_ZERO_SIZE +
    (MAX_AUTH_DATA_PAGES - 1) * MAX_AUTH_PAGE_NON_ZERO_SIZE;
const MAX_MESSAGES_IN_PACK = 9;
const MAX_MESSAGE_PACK_SIZE = MAX_MESSAGE_SIZE * MAX_MESSAGES_IN_PACK;
const LAT_LONG_MULTIPLIER = 1e-7;
const MIN_DIR = 0; // Minimum direction
const MAX_DIR = 360; // Maximum direction
const INV_DIR = 361; // Invalid direction
const MIN_SPEED_H = 0; // Minimum speed horizontal
const MAX_SPEED_H = 254.25; // Maximum speed horizontal
const INV_SPEED_H = 255; // Invalid speed horizontal
const MIN_SPEED_V = (-62); // Minimum speed vertical
const MAX_SPEED_V = 62; // Maximum speed vertical
const INV_SPEED_V = 63; // Invalid speed vertical
const MIN_LAT = -90; // Minimum latitude
const MAX_LAT = 90; // Maximum latitude
const INV_LAT = 0; // Invalid latitude
const MIN_LON = -180; // Minimum longitude
const MAX_LON = 180; // Maximum longitude
const INV_LON = 0; // Invalid longitude
const MIN_ALT = (-1000); // Minimum altitude
const MAX_ALT = 31767.5; // Maximum altitude
const INV_ALT = MIN_ALT; // Invalid altitude
const MAX_TIMESTAMP = (60 * 60);
const INV_TIMESTAMP = 0xFFFF; // Invalid, No Value or Unknown Timestamp
const MAX_AREA_RADIUS = 2550;
